apiVersion: apps/v1
kind: Deployment
metadata:mychatbot
  name: 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mychatbot
  template:
    metadata:
      labels:
        app: mychatbot
    spec:
      containers:
        - name: mychatbot
          image: "{{ if .Values.registry }}{{ .Values.registry }}/{{ end }}mychatbot:{{ .Values.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mychatbot-secrets
                  key: OPENAI_API_KEY
            - name: OPENAI_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: mychatbot-secrets
                  key: OPENAI_PROJECT_ID
            - name: MILVUS_HOST
              value: "{{ .Values.milvus.host }}"
            - name: MILVUS_PORT
              value: "{{ .Values.milvus.port }}"
            - name: SEMANTIC_LLM_MODEL_PATH
              value: /models/llama-2-7b-chat.Q4_K_M.gguf
          volumeMounts:
            - name: models
              mountPath: /models
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: models-pvc