apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-ui
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: agent-ui
  template:
    metadata:
      labels:
        app: agent-ui
    spec:
      containers:
        - name: agent-ui
          image: "{{ if .Values.registry }}{{ .Values.registry }}/{{ end }}agent-ui:{{ .Values.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: AI_SERVICE_HOST
              value: "{{ .Values.aiService.host }}"
            - name: AI_SERVICE_PORT
              value: "{{ .Values.aiService.port }}"
