apiVersion: v1
kind: Service
metadata:
  name: agent-ui
spec:
  selector:
    app: agent-ui
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
