name: "Local context setup"
description: "Sets kubeconfig for minikube"

runs:
  using: "composite"
  steps:
    - name: Copy kubeconfig
      shell: bash
      run: |
        mkdir -p ~/.kube
         cp /kube/config ~/.kube/config
        chmod 600 ~/.kube/config
        echo "KUBECONFIG set for local kube"
        kubectl config use-context minikube || true

    - name: Verify kubectl
      shell: bash
      run: kubectl get nodes
