name: Authenticate to GCP GKE

on:
  workflow_call:

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GCP_REGION }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Verify kubectl
        run: kubectl get nodes
